templates:
  deluge_basic:
    deluge:
      path: /media/HardDrive/Torrents/
      host:
      port:
      username:
      password:

tasks:
  Dan:
    template: deluge_basic
    deluge:
      main_file_only: yes
      label: FlexgetTV
    no_entries_ok: yes
    content_filter:
      reject:
        - '*.rar'
        - '*.r00'
        - '*.r01'
        - 'password.txt'
    configure_series:
      settings:
        target: 720p+
        timeframe: 1 days
        propers: no
        upgrade: yes
        set:
          move_completed_path: /media/HardDrive/Videos/Television/{{series_name}}/Season {{series_season}}/
          content_filename: "{{series_name}} - {{series_id}}"
      from:
        csv:
          url: 'file:///root/.flexget/shows.csv'
          values:
            title: 1
            url: 1   
    discover:
      what:
        - next_series_episodes:
            from_start: yes
      from:
        - rarbg:
            sorted_by: seeders
            use_tvdb: True
            category: [18, 41, 49]
#               18 = TV Episodes, 41 = TV HD Episodes, 49 = TV UHD Episodes
        - 1337x: yes
        - limetorrents:
            category: tv
            order_by: seeds
#        - piratebay: yes

